name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: flowershop-morales

    - name: Configure Docker to use gcloud credentials
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/flowershop-morales/flower-api/flowershop-api:latest .
        docker push us-central1-docker.pkg.dev/flowershop-morales/flower-api/flowershop-api:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flowershop-api \
          --image us-central1-docker.pkg.dev/flowershop-morales/flower-api/flowershop-api:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --memory 512Mi \
          --port 8080 \
          --service-account api-flowershop-admin@flowershop-morales.iam.gserviceaccount.com \
          --timeout 300s \
          --set-env-vars ASPNETCORE_ENVIRONMENT=Production,DB_PROVIDER=Postgres \
          --set-secrets CONNECTION_STRING=db-connection-string:latest